# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Release Artifacts

on:
  push:
    tags: ['*']
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./dist/videojs-markers.js, ./dist/videojs-markers.js.map, ./dist/videojs-markers.css, ./dist/types.d.ts, LICENSE-MIT"
